### ISSUE TITLE
Urgent!! Can you provide the data you have used.

### ISSUE THREAD

**Issue by entbappy** [asimokby/cv-parser-huggingface#1]
We are working on the same use case,, Actually, we are a little bit confused regarding the dataset format, We would be glad if you share your data. Thanks

**Comment by asimokby** [comment]
No dataset was used as it is clear that the tool is built using pre-trained models.

If you are fine-tuning a model for a text-classification task, you could annotate the lines of CVs and use each labeled line as a training example.
